version: "3.8"

services:
  upkeep:
    image: kodaxx/upkeep:latest
    container_name: upkeep
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /mnt/user/appdata/upkeep:/app/data
    environment:
      - TZ=America/Denver # Adjust to your timezone
      - PUID=99 # Default Unraid user ID
      - PGID=100 # Default Unraid group ID
      - UMASK=002 # Default Unraid umask
    network_mode: bridge
